import { defineCollection, z } from 'astro:content';

const blogCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    publishedDate: z.date(),
    updatedDate: z.date().optional(),
    author: z.string(),
    image: z.string().optional(),
    tags: z.array(z.string()).optional(),
    draft: z.boolean().default(false),
    featured: z.boolean().default(false)
  })
});

const pageCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    image: z.string().optional(),
    noindex: z.boolean().default(false)
  })
});

// Bonuses Collection (Programmatic SEO)
const bonusesCollection = defineCollection({
  schema: z.object({
    title: z.string(),
    description: z.string(),
    // slug is auto-generated by Astro from filename
    geo: z.array(z.string()),
    bonusType: z.enum(['welcome', 'reload', 'free-spin', 'cashback', 'no-wagering', 'deposit', 'no-deposit']),
    wagering: z.string(),
    pros: z.array(z.string()),
    cons: z.array(z.string()),
    riskLevel: z.enum(['low', 'medium', 'high']).optional(),
    suitableFor: z.array(z.string()).optional(),
    notSuitableFor: z.array(z.string()).optional(),
    keywords: z.array(z.string()).optional(),
    
    // Deduplication fields (anti-thin content)
    contentAngle: z.enum(['beginner-guide', 'risk-analysis', 'comparison-focused', 'expert-deep-dive', 'quick-reference']).default('beginner-guide'),
    searchDemand: z.enum(['high', 'medium', 'low', 'none']).default('medium'),
    shouldIndex: z.boolean().default(true),
    uniqueValue: z.string().optional(),
    
    // Lifecycle Management (Kill-Switch)
    lifecycleStatus: z.enum(['active', 'under-review', 'retired', 'archived']).default('active'),
    retirementReason: z.string().optional(),
    
    // Content Freshness Signals
    publishedAt: z.date().optional(),
    updatedAt: z.date().optional(),
    lastReviewedAt: z.date().optional(),
    nextReviewDate: z.date().optional(),
    contentVersion: z.string().default('1.0'),
    
    // E-E-A-T Author Layer
    author: z.object({
      name: z.string(),
      slug: z.string(),
      title: z.string(),
      experience: z.string(),
    }).default({
      name: 'Maxwin580 Editöryal Ekibi',
      slug: 'editorial-team',
      title: 'Editorial Team',
      experience: 'Sektör uzmanları',
    }),
    reviewedBy: z.string().optional(),
    
    // Internal Link Throttling
    parentHub: z.string().default('/bonuses'),
    relatedPages: z.array(z.string()).max(5).default([]),
    linkPriority: z.enum(['high', 'medium', 'low']).default('medium'),
  }),
});

// Geo-Specific Bonuses Collection (Country-based pages)
const bonusesGeoCollection = defineCollection({
  schema: z.object({
    title: z.string(),
    description: z.string(),
    bonusSlug: z.string(),
    country: z.string(),
    countryName: z.string(),
    localizedIntro: z.string(),
    legalDisclaimer: z.string(),
    availabilityStatus: z.enum(['available', 'restricted', 'requires-verification', 'unclear']),
    localRegulations: z.string().optional(),
    faq: z.array(z.object({
      question: z.string(),
      answer: z.string()
    })),
    keywords: z.array(z.string()).optional(),
    
    // Canonical Strategy for Variants
    canonicalStrategy: z.enum(['self', 'parent', 'hub']).default('self'),
    canonicalOverride: z.string().optional(),
    contentUniqueness: z.enum(['high', 'medium', 'low']).default('medium'),
    shouldIndex: z.boolean().default(true),
    searchDemand: z.enum(['high', 'medium', 'low', 'none']).default('medium'),
    
    // Lifecycle Management
    lifecycleStatus: z.enum(['active', 'under-review', 'retired', 'archived']).default('active'),
    
    // Content Freshness
    publishedAt: z.date().optional(),
    updatedAt: z.date().optional(),
    lastReviewedAt: z.date().optional(),
    contentVersion: z.string().default('1.0'),
    
    // E-E-A-T
    author: z.object({
      name: z.string(),
      slug: z.string(),
      title: z.string(),
      experience: z.string(),
    }).default({
      name: 'Maxwin580 Editöryal Ekibi',
      slug: 'editorial-team',
      title: 'Editorial Team',
      experience: 'Sektör uzmanları',
    }),
    reviewedBy: z.string().optional(),
    
    // Link Throttling
    parentHub: z.string().default('/bonuses'),
    relatedPages: z.array(z.string()).max(5).default([]),
  }),
});

// Intent-Based Collections (Search Intent Isolation)

// Informational Intent - Educational guides
const bonusGuidesCollection = defineCollection({
  schema: z.object({
    title: z.string(),
    description: z.string(),
    // slug is auto-generated by Astro from filename
    intent: z.literal('informational'),
    
    // Content
    topic: z.string(),
    difficulty: z.enum(['beginner', 'intermediate', 'advanced']).default('beginner'),
    
    // Freshness
    publishedAt: z.date(),
    updatedAt: z.date(),
    
    // E-E-A-T
    author: z.object({
      name: z.string(),
      slug: z.string(),
      title: z.string(),
      experience: z.string(),
    }).default({
      name: 'Maxwin580 Editöryal Ekibi',
      slug: 'editorial-team',
      title: 'Editorial Team',
      experience: 'Sektör uzmanları',
    }),
    
    // SEO
    keywords: z.array(z.string()).optional(),
    shouldIndex: z.boolean().default(true),
    searchDemand: z.enum(['high', 'medium', 'low', 'none']).default('medium'),
    
    // Linking
    parentHub: z.string().default('/bonuses/guide'),
    relatedPages: z.array(z.string()).max(5).default([]),
  }),
});

// Commercial Intent - Comparison content
const bonusComparisonsCollection = defineCollection({
  schema: z.object({
    title: z.string(),
    description: z.string(),
    // slug is auto-generated by Astro from filename
    intent: z.literal('commercial'),
    
    // Comparison specifics
    comparisonType: z.enum(['vs', 'best-for', 'ranking', 'overview']),
    itemsCompared: z.array(z.string()),
    
    // Freshness
    publishedAt: z.date(),
    updatedAt: z.date(),
    
    // E-E-A-T
    author: z.object({
      name: z.string(),
      slug: z.string(),
      title: z.string(),
      experience: z.string(),
    }).default({
      name: 'Maxwin580 Editöryal Ekibi',
      slug: 'editorial-team',
      title: 'Editorial Team',
      experience: 'Sektör uzmanları',
    }),
    
    // SEO
    keywords: z.array(z.string()).optional(),
    shouldIndex: z.boolean().default(true),
    searchDemand: z.enum(['high', 'medium', 'low', 'none']).default('medium'),
    
    // Linking
    parentHub: z.string().default('/bonuses/comparison'),
    relatedPages: z.array(z.string()).max(5).default([]),
  }),
});

export const collections = {
  blog: blogCollection,
  pages: pageCollection,
  bonuses: bonusesCollection,
  'bonuses-geo': bonusesGeoCollection,
  'bonus-guides': bonusGuidesCollection,
  'bonus-comparisons': bonusComparisonsCollection,
};
